export const statusBadgeColors = {
     "IN PROGRESS" : "bg-blue-50 text-blue-700 dark:bg-blue-950 dark:text-blue-300",
     DONE:"bg-green-50 text-green-700 dark:bg-green-950 dark:text-green-300",
     "TO DO":"bg-secondary text-secondary-foreground [a]:hover:bg-secondary/80"
}


export const METADATA_COLORS = [
  {
    id: 1,
    name: "Slate Gray",
    text: "#6B7280",
    bg: "#F1F5F9",
    bg_name: "Light Grey",
  },
  {
    id: 2,
    name: "Blue",
    text: "#1D4ED8",
    bg: "#EFF6FF",
    bg_name: "Light Blue",
  },
  {
    id: 3,
    name: "Purple",
    text: "#9747FF",
    bg: "#F3E8FF",
    bg_name: "Light Purple",
  },
  {
    id: 4,
    name: "Green",
    text: "#16A34A",
    bg: "#DCFCE7",
    bg_name: "Light Green",
  },
  {
    id: 5,
    name: "Yellow",
    text: "#EAB308",
    bg: "#FEF9C3",
    bg_name: "Light Yellow",
  },
  {
    id: 6,
    name: "Red",
    text: "#EF4444",
    bg: "#FCE7F3",
    bg_name: "Light Red",
  },
  {
    id: 7,
    name: "White",
    text: "#FFFFFF",
    bg: "#334155",
    bg_name: "Dark Grey",
  },
  {
    id: 8,
    name: "White",
    text: "#FFFFFF",
    bg: "#1D4ED8",
    bg_name: "Blue Primary",
  },
  {
    id: 9,
    name: "White",
    text: "#FFFFFF",
    bg: "#9333EA",
    bg_name: "Purple Deep",
  },
  {
    id: 10,
    name: "White",
    text: "#FFFFFF",
    bg: "#16A34A",
    bg_name: "Green",
  },
  {
    id: 11,
    name: "White",
    text: "#FFFFFF",
    bg: "#F59E0B",
    bg_name: "Amber",
  },
  {
    id: 12,
    name: "White",
    text: "#FFFFFF",
    bg: "#E11D48",
    bg_name: "Red",
  },
  {
    id: 13,
    name: "White",
    text: "#FFFFFF",
    bg: "#99660F",
    bg_name: "Brown Gold",
  },
  {
    id: 14,
    name: "White",
    text: "#FFFFFF",
    bg: "#AD3BB3",
    bg_name: "Magenta",
  },
  {
    id: 15,
    name: "White",
    text: "#FFFFFF",
    bg: "#FF7291",
    bg_name: "Soft Pink",
  },
  {
    id: 16,
    name: "White",
    text: "#FFFFFF",
    bg: "#4D7C6F",
    bg_name: "Teal Muted",
  },
  {
    id: 17,
    name: "White",
    text: "#FFFFFF",
    bg: "#16B0B5",
    bg_name: "Teal Aqua",
  },
  {
    id: 18,
    name: "White",
    text: "#FFFFFF",
    bg: "#7C6DAA",
    bg_name: "Indigo Muted",
  },
  {
    id: 19,
    name: "Brown Gold",
    text: "#99660F",
    bg: "#FBECD1",
    bg_name: "Beige",
  },
  {
    id: 20,
    name: "Magenta",
    text: "#AD3BB3",
    bg: "#FEE8FF",
    bg_name: "Lavender Blush",
  },
  {
    id: 21,
    name: "Soft Pink",
    text: "#FF7291",
    bg: "#FFE6EC",
    bg_name: "Pink",
  },
  {
    id: 22,
    name: "Orange",
    text: "#B54E16",
    bg: "#FFD2B5",
    bg_name: "Soft Orange",
  },
  {
    id: 23,
    name: "Teal Green",
    text: "#4D7C6F",
    bg: "#B8E4D8",
    bg_name: "Mint Green",
  },
  {
    id: 24,
    name: "Muted Indigo",
    text: "#7B6CA9",
    bg: "#E3DAFF",
    bg_name: "Indigo",
  },
];